---
- name: "Add python repository"
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
  tags: "addrep"

- name: "Installing latest python and pip"
  ansible.builtin.apt:
    name: '{{ packages }}'
    state: present
    update_cache: true
  tags: "pyins"

- name: "Upgrading system"
  ansible.builtin.apt:
    upgrade: dist
  tags: "Sysupgrade"
